name: DigitSec Security Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/digitsec-security-scan
        with:
          s4-api-token: ${{ secrets.S4_API_TOKEN }}
          s4-org-id: '<orgId from step 3>'
          s4-base-url: 'https://greeting-easy-developer-printer.trycloudflare.com'
